# Generated by Django 3.2.12 on 2022-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
